### ISSUE TITLE
Refactor build process

### ISSUE THREAD

**Issue by thetazero** [PyCubed-Mini/software_example_beepsat#26]
Currently there is a large amount of identical files scattered along the repository.
We have the code split into the "frame" and the "plugins"

But there seem to be 3 real components
- The hardware drivers (or the emulator)
- The implementation (what it tries to do with the "hardware")
- The framework (shared across all)

Perhaps we should split the code into 3 separate components like that?

**Comment by jbwillis** [comment]
I'm liking this.

Can you describe what would fall into each for the example plugin, just so I understand exactly where you want to divide things?

**Comment by thetazero** [comment]
Sure:
drivers: pycubedmini.py (or emulator), most lib files (like rmf9x, bitflags, etc...)
implementation: All the tasks, state machine config
frame: same as before
