### ISSUE TITLE
pycubed.py todo: implement backup import

### ISSUE THREAD

**Issue by yashikabatra15** [PyCubed-Mini/software_example_beepsat#42]
taken from comments in pycubed.py:

imports = ['sys', 'os', 'miconctroller']
modules = []
for x in imports:
    try:
        modules.append(__import__(x))
        print("Successfully imported ", x)
    except ImportError:
        print("Error importing ", x)

**Comment by thetazero** [comment]
I disagree with the need for this.

**Comment by yashikabatra15** [comment]
It was part of the comments in pycubedmini.py so I thought I'd create an issue for it -- seemed like a better avenue for discussion than leaving it in the file unaddressed. I also don't see much of a need for it.

**Comment by thetazero** [comment]
Fair enough, I'd run it by Jacob and if he doesn't see a reason to implement it I think we are good.

**Comment by yashikabatra15** [comment]
Sounds good

**Comment by jbwillis** [comment]
Can you give a bit more context for me? Is this code that is running, or old commented out code? What was its purpose? Why don't you think it's needed?

**Comment by yashikabatra15** [comment]
It wouldn't be able to resolve the import error, and then it would terminate the running process. I think the only scenario where this would be useful is if we have multiple libraries that are able to provide the same functionality (in which case, if 1 import fails, the other would be imported). I feel like this doesn't really apply to our use case though. I'm happy to reach out to Max and ask what his intention with this comment was.

**Comment by jbwillis** [comment]
Yeah, that’s what I figured. Let’s just delete it.
