### ISSUE TITLE
Better state machine example

### ISSUE THREAD

**Issue by jbwillis** [PyCubed-Mini/software_example_beepsat#9]
If the example plugin is meant to provide a minimum working example of the state machine, I think it needs to be pared down some. Let's make it agnostic to the fact that this is even satellite code. Just create a few tasks with overly verbose names and varying frequencies/delays. Here's a suggestion

- `repeat_every_5_seconds_task`
- `repeat_every_10_seconds_start_later_task`
- etc (as needed to demonstrate functionality)

**Comment by thetazero** [comment]
Created a draft pull in #10, still need to proof read the README. 

I intentionally left some very minimum satellite things in the code in order to demonstrate that in tasks you can still do things like read battery voltage or get uptime.
